# Generated by Django 5.1.6 on 2025-03-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablou',
            name='descriere',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablou',
            name='titlu',
            field=models.CharField(max_length=255),
        ),
    ]
