# Generated by Django 5.1.6 on 2025-03-11 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0002_tablou_descriere_alter_tablou_titlu'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablou',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comentariu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tablou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarii', to='galerie.tablou')),
            ],
        ),
    ]
