# Generated by Django 5.1.6 on 2025-03-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0003_tablou_likes_comentariu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablou',
            name='descriere',
            field=models.TextField(default='fara descriere'),
        ),
    ]
