# Generated by Django 5.1.7 on 2025-03-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proiect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=100)),
                ('descriere', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('imagine', models.ImageField(blank=True, upload_to='proiecte/')),
            ],
        ),
    ]
