# Generated by Django 5.1.7 on 2025-03-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofoliu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proiect',
            name='categorie',
            field=models.CharField(choices=[('creion', 'Desene în creion'), ('ulei', 'Picturi în ulei'), ('portret', 'Portrete'), ('ilustratie', 'Ilustrații'), ('nft', 'NFT-uri')], default='creion', max_length=50),
            preserve_default=False,
        ),
    ]
